name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # ------------------ SONARQUBE ------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://<YOUR-SONAR-IP>:9000

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # ------------------ SNYK ------------------
      - name: Install Snyk
        run: npm install -g snyk

      - name: Snyk Dependency Security Scan
        run: snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ------------------ BUILD ARTIFACT ------------------
      - name: Build artifact (zip app)
        run: zip -r app-artifact.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app-artifact
          path: app-artifact.zip


  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci
      - run: npm test


  docker-build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t suyog18/k8s-nodejs-app:latest .

      #SNYK DOCKER SCAN (AFTER BUILD)
      - name: Snyk Docker Security Scan
        run: snyk container test suyog18/k8s-nodejs-app:latest
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Push Docker image
        run: docker push suyog18/k8s-nodejs-app:latest


  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:

      - uses: actions/checkout@v4

      - name: Setup KIND Kubernetes cluster
        uses: helm/kind-action@v1.8.0

      - name: Verify cluster
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f deploymentservice.yaml

      - name: Wait for deployment
        run: kubectl rollout status deployment/k8-nodejs-app-deployment --timeout=120s

      - name: Verify resources
        run: |
          kubectl get pods
          kubectl get svc

      - name: Verify app
        run: |
          kubectl port-forward svc/nodeapp-service 5000:5000 &
          sleep 8
          curl http://localhost:5000


  #DAST (AFTER DEPLOYMENT)
  dast:
    runs-on: ubuntu-latest
    needs: deploy
    steps:

      - name: DAST Scan (OWASP ZAP)
        run: |
          docker run --rm -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://3.108.235.107:5000 -I
