name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: SonarQube Scan
        run: echo "Sonar step ready (will activate after token)"

      - name: Install Snyk
        run: npm install -g snyk

      - name: Snyk Dependency Security Scan
        run: snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Docker Security Scan
        run: snyk container test nodeapp:latest
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: DAST Scan (OWASP ZAP)
        run: |
          docker run -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://3.108.235.107:5000/


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build artifact (zip app)
        run: zip -r app-artifact.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app-artifact
          path: app-artifact.zip

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t suyog18/k8s-nodejs-app:latest .

      - name: Push Docker image
        run: docker push suyog18/k8s-nodejs-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup KIND Kubernetes cluster
        uses: helm/kind-action@v1.8.0

      - name: Verify cluster
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f deploymentservice.yaml

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/k8-nodejs-app-deployment --timeout=120s

      - name: Verify Kubernetes resources
        run: |
          kubectl get pods
          kubectl get svc

      - name: Verify app via port-forward
        run: |
          kubectl port-forward svc/nodeapp-service 5000:5000 &
          sleep 5
          curl http://localhost:5000
