name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # SONARQUBE
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      #SNYK DEPENDENCY SCAN (NON-BLOCKING)
      - name: Install Snyk
        run: npm install -g snyk

      - name: Snyk Dependency Security Scan (Non-blocking)
        run: snyk test --severity-threshold=critical || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---------------- BUILD ARTIFACT ----------------
      - name: Build artifact (zip app)
        run: zip -r app-artifact.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app-artifact
          path: app-artifact.zip


  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci
      - run: npm test


  docker-build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t suyog18/k8s-nodejs-app:latest .

      # ---------------- SNYK DOCKER SCAN (NON-BLOCKING) ----------------
      - name: Install Snyk
        run: npm install -g snyk

      - name: Snyk Docker Security Scan (Non-blocking)
        run: snyk container test suyog18/k8s-nodejs-app:latest --file=Dockerfile || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Push Docker image
        run: docker push suyog18/k8s-nodejs-app:latest


  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:

      - uses: actions/checkout@v4

      - name: Setup KIND Kubernetes cluster
        uses: helm/kind-action@v1.8.0

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Verify cluster
        run: kubectl cluster-info

      - name: Wait for Kubernetes
        run: kubectl wait --for=condition=Ready nodes --all --timeout=120s

      - name: Deploy using Helm
        run: helm upgrade --install nodeapp ./nodeapp-chart

      - name: Wait for deployment
        run: kubectl rollout status deployment/nodeapp-nodeapp-chart --timeout=180s

      - name: Verify resources
        run: |
          kubectl get pods
          kubectl get svc
          
      - name: Verify app
        run: |
          kubectl port-forward svc/nodeapp-service 5000:5000 &
          sleep 8
          curl http://localhost:5000


  #DAST
  dast:
    runs-on: ubuntu-latest
    needs: deploy
    steps:

      - name: DAST Scan (OWASP ZAP)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://3.108.235.107:5000'

